[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night_storm.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions = { columns = 150, lines = 50}
# decorations = "Buttonless"
# make it always centered
# dynamic_padding = true

opacity = 0.5
blur = true

option_as_alt = "Both"

[font]

normal.family = "JetBrainsMono Nerd Font"
size = 18

